language: python
python:
  - "3.5"
env:
  - DJANGO_VERSION=1.10.2
install:
  - pip install -q Django==$DJANGO_VERSION
  - pip install mysql-python
# - python setup.py -q install
# - pip install -r travis
script:
  - python fitster/manage.py test home